before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - main: ./cmd/w2ctl
    env:
     - CGO_ENABLED=1
    goos:
     - linux
     - windows
     - darwin
    id: "w2ctl"
    binary: w2ctl
    flags:
      - -trimpath
    overrides:
      - goos: darwin
        goarch: arm64
        goarm: ''
        gomips: ''
        ldflags:
          - foo
        tags:
          - bar
        asmflags:
          - foobar
        gcflags:
          - foobaz

  - main: ./cmd/w2psd
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    id: "w2psd"
    binary: w2psd
    flags:
      - -trimpath
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
