[domain]
name = "xxxxxxxx系统"
[scrape]
# minute interval
interval = 10
[alert]
notify = true
ignore_time = ["05:00-07:00"]
# alertmanager url
url = "http://127.0.0.1:9093/api/v1/alerts"
[mail]
send = false
cron = "16 16 * * *"
server = "your.mail-domain.com"
port = 25
user = "you account"
passwd = "your password"
to = "destnation"
[report]
title = "巡检报告"
reporter = "richard"

# processes
# one host
[[data.processes]]
host = "192.168.1.41:22"

[[data.processes.process]]
osuser = "oracle"
name = "oracle"
path = ""
pidfile = ""
ports = [22, 21]
group = "oracle"
flag = "pmon"

[[data.processes.process]]
name = "deal"
osuser= "oracle"
path = ""
pidfile = ""
ports = []
group = "oracle"
flag = "pmon"

[[data.processes]]
host = "192.168.1.41:22"
[[data.processes.process]]
osuser = "root"
name = "oracle"
path = ""
pidfile = ""
ports = [22, 21]
group = "ttttttt"
flag = "mashaji"



#another host
[[data.processes]]
host = "192.168.1.41:22"

[[data.processes.process]]
name = "oracle"
osuser = "root"
path = ""
pidfile = ""
ports = [22]
group = "AAAAA"
flag = "pmon"