# the target of alert
[alert]
notify = false
url = "http://172.16.18.200:9093/api/v1/alerts"
# mail config
[mail]
send = false
cron = "00 7 * * *"
server = ""
port = 25
user = ""
passwd = ""
to = ""

[report]
title = "HFP巡检报告"
reporter = "高运金融"
# process config
[[data.processes]]
host = "192.168.0.127"
[[data.processes.process]]
name = "docker"
path = "/opt/kube/bin/dockerd"
pidfile = ""
ports = [22, 21]
group = "hfp"
flag = "/opt/kube/bin/dockerd"
[[data.processes.process]]
name = "B"
path = ""
pidfile = ""
ports = [22, 21]
group = "ph"
flag = "sssssssss"

[[data.processes]]
host = "192.168.1.41"
[[data.processes.process]]
name = "oracle"
path = ""
pidfile = ""
ports = [22, 21]
group = "oracle"
flag = "pmon"