[mail]
send = true
cron = ""
user = "liupeng@auto-fis.com"
passwd = ""
to = ""

[[data.processes]]
host = "192.168.0.127"
[[data.processes.process]]
name = "docker"
path = "/opt/kube/bin/dockerd"
pidfile = ""
ports = [22, 21]
group = "hfp"
flag = "/opt/kube/bin/dockerd"
[[data.processes.process]]
name = "B"
path = ""
pidfile = ""
ports = [22, 21]
group = "ph"
flag = "sssssssss"

[[data.processes]]
host = "192.168.1.41"
[[data.processes.process]]
name = "oracle"
path = ""
pidfile = ""
ports = [22, 21]
group = "oracle"
flag = "pmon"